language: java
jdk: oraclejdk7

# whitelist
branches:
    only:
        - master

env:
  matrix:
    - ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a

before_install:
  # Install base Android SDK
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs lib32z1 ia32-libs-multiarch > /dev/null; fi
  - wget http://dl.google.com/android/android-sdk_r23-linux.tgz
  - tar xzf android-sdk_r23-linux.tgz
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools

  # Install required components.
  # Note that sysimg-19 downloads only ARM, because only the first license query is accepted.
  - echo yes | android update sdk --filter platform-tools --no-ui --force > /dev/null
  - echo yes | android update sdk --all --filter build-tools-21.1.2 --no-ui --force > /dev/null
  - echo yes | android update sdk --filter android-21 --no-ui --force > /dev/null
  - echo yes | android update sdk --filter sysimg-21 --no-ui --force > /dev/null
  - echo yes | android update sdk --filter extra-android-support --no-ui --force > /dev/null
  - echo yes | android update sdk --filter extra-android-m2repository --no-ui --force > /dev/null
  - echo yes | android update sdk --filter extra-google-m2repository --no-ui --force > /dev/null

install:
    - TERM=dumb ./gradlew clean assembleDebug -PdisablePreDex

script:
    - TERM=dumb ./gradlew check --info

deploy:
    provider: releases
    file:
        - app/build/outputs/apk/app-release.apk
        - app/build/outputs/apk/app-debug.apk
    skip_cleanup: true
    on:
        tags: true
        branch: master
